# Nixpacks configuration for Railway deployment with TensorFlow.js and image processing support

[phases.setup]
nixPkgs = [
    'nodejs-18_x'
]

[phases.install]
cmds = [
    'npm ci --only=production --no-audit --no-fund --ignore-optional || npm ci --only=production --no-audit --no-fund'
]

[variables]
NODE_ENV = 'production'
NPM_CONFIG_CACHE = '/tmp/.npm'
PYTHON = 'python3'

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'