# Nixpacks configuration for Railway deployment with TensorFlow.js and image processing support

[phases.setup]
nixPkgs = [
    'nodejs-18_x',
    'python3',
    'pkg-config',
    'make',
    'gcc',
    'g++',
    'libjpeg',
    'libpng'
]

[phases.install]
cmds = [
    'rm -rf node_modules/.cache || true',
    'npm ci --only=production --no-audit --no-fund --ignore-optional --cache=/tmp/.npm'
]

[variables]
NODE_ENV = 'production'
NPM_CONFIG_CACHE = '/tmp/.npm'
PYTHON = 'python3'
# Prevent cache conflicts in Railway builds
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'
NPM_CONFIG_AUDIT = 'false'

[phases.build]
cmds = [
    'rm -rf node_modules/.cache || true',
    'npm run build'
]

[start]
cmd = 'npm start'