# Nixpacks configuration for Railway deployment - no cache mounts to avoid exit code 240

[phases.setup]
nixPkgs = [
    'nodejs-18_x',
    'python3',
    'pkg-config',
    'make',
    'gcc',
    'g++',
    'libjpeg',
    'libpng'
]

[phases.install]
cmds = ['npm ci --only=production --no-audit --no-fund --ignore-optional']

[phases.build] 
cmds = ['npm run build']

[variables]
NODE_ENV = 'production'
PYTHON = 'python3'
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'
NPM_CONFIG_AUDIT = 'false'
# Build signature to ensure fresh deployment
BUILD_SIGNATURE = '20250825_NO_CACHE_MOUNT_FIX'

[start]
cmd = 'npm start'