# Nixpacks configuration for Railway deployment with OpenCV support

[phases.setup]
nixPkgs = [
    'nodejs-18_x',
    'python3',
    'cmake',
    'gcc',
    'gnumake',
    'pkg-config',
    'opencv4',
    'libopencv',
    'glib',
    'glibc'
]

[phases.install]
cmds = [
    # Set up proper environment for opencv4nodejs
    'export OPENCV4NODEJS_DISABLE_AUTOBUILD=1',
    'export OPENCV_INCLUDE_DIR="/nix/store/$(ls /nix/store | grep opencv4 | head -1)/include/opencv4"',
    'export OPENCV_LIB_DIR="/nix/store/$(ls /nix/store | grep opencv4 | head -1)/lib"',
    'export PKG_CONFIG_PATH="/nix/store/$(ls /nix/store | grep opencv4 | head -1)/lib/pkgconfig:$PKG_CONFIG_PATH"',
    # Install dependencies with proper environment
    'npm ci --verbose'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'