# Nixpacks configuration for Railway deployment with TensorFlow.js support

[phases.setup]
nixPkgs = [
    'nodejs-18_x',
    'python3'
]

[phases.install]
cmds = [
    'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'